import time
from datetime import date, datetime

import requests

projects = [
    ("lpil", "aws4_request"),
    ("Cyteon", "discord_gleam"),
    ("lpil", "glatus"),
    ("gleam-lang", "hexpm"),
    ("bunopnu", "glevatar"),
    ("stevetoro", "tallgrass"),
    ("bondiano", "telega-gleam"),
    ("schurhammer", "gleamy_bench"),
    ("inoas", "glychee"),
    ("Enderchief", "esgleam"),
    ("lpil", "gleescript"),
    ("lpil", "argv"),
    ("drewolson", "clip"),
    ("gleam-community", "ansi"),
    ("TanklesXL", "glint"),
    ("miampf", "glitzer"),
    ("tynanbe", "rad"),
    ("tynanbe", "shellout"),
    ("lpil", "spinner"),
    ("olian04", "gleam-stdin"),
    ("aosasona", "dotenv"),
    ("Grubba27", "dotenv_gleam"),
    ("lpil", "envoy"),
    ("custompro98", "glenv"),
    ("maxdeviant", "glenvy"),
    ("Pevensie", "argus"),
    ("lpil", "beecrypt"),
    ("gleam-lang", "crypto"),
    ("rvcas", "ids"),
    ("mdarse", "kmh"),
    ("lpil", "youid"),
    ("MystPi", "act"),
    ("tynanbe", "argamak"),
    ("bwireman", "delay"),
    ("gleam-lang", "stdlib"),
    ("mrdimosthenis", "gleam_zlists"),
    ("schurhammer", "gleamy_structures"),
    ("fschwalbe", "glearray"),
    ("bwireman", "gleither"),
    ("giacomocavalieri", "non_empty_list"),
    ("giacomocavalieri", "tote"),
    ("giacomocavalieri", "trie_again"),
    ("inoas", "gleam-cake"),
    ("aosasona", "migrant"),
    ("massivefermion", "mungo"),
    ("daniellionel01", "parrot"),
    ("lpil", "pog"),
    ("massivefermion", "radish"),
    ("lpil", "sqlight"),
    ("giacomocavalieri", "squirrel"),
    ("lpil", "storail"),
    ("Pevensie", "valkyrie"),
    ("gideongrinberg", "gcourier"),
    ("lpil", "gleam_sendgrid"),
    ("aosasona", "plunk.gleam"),
    ("lpil", "zeptomail"),
    ("renatillas", "eventsourcing"),
    ("Pevensie", "barnacle"),
    ("Pevensie", "bath"),
    ("grottohub", "carpenter"),
    ("chouzar", "chip"),
    ("gleam-lang", "erlang"),
    ("gleam-lang", "otp"),
    ("Pevensie", "lifeguard"),
    ("ckreiling", "nessie_cluster"),
    ("lpil", "process-waiter"),
    ("massivefermion", "puddle"),
    ("maxdeviant", "shakespeare"),
    ("JonasGruenwald", "spectator"),
    ("lpil", "exception"),
    ("gleam-experiments", "snag"),
    ("richard-viney", "file_streams"),
    ("lpil", "filepath"),
    ("bcpeinhardt", "simplifile"),
    ("mscharley", "gleam-commonmark"),
    ("lpil", "cymbal"),
    ("bcpeinhardt", "gsv"),
    ("richard-viney", "iso_8859"),
    ("lpil", "jot"),
    ("lpil", "tom"),
    ("lpil", "xmb"),
    ("okkdev", "glailglind"),
    ("ghivert", "grille-pain"),
    ("lustre-labs", "lustre"),
    ("lustre-labs", "lustre_ui"),
    ("schurhammer", "lustre_virtual_list"),
    ("ghivert", "redraw"),
    ("ghivert", "sketch"),
    ("ghivert", "tardis"),
    ("lpil", "glance"),
    ("bcpeinhardt", "glance_printer"),
    ("gleam-lang", "package-interface-decoder"),
    ("DanielleMaywood", "glexer"),
    ("MystPi", "pprint"),
    ("tinybackup", "ansel"),
    ("gleam-community", "colour"),
    ("lpil", "formal"),
    ("giacomocavalieri", "houdini"),
    ("lpil", "htmb"),
    ("lpil", "htmgrrrl"),
    ("nakaixo", "nakai"),
    ("strawmelonjuice", "odysseus"),
    ("ghivert", "cors-builder"),
    ("gleam-lang", "http"),
    ("gleam-lang", "fetch"),
    ("gleam-lang", "hackney"),
    ("gleam-lang", "httpc"),
    ("lpil", "cgi"),
    ("vshakitskiy", "ewe"),
    ("gleam-lang", "elli"),
    ("rawhat", "mist"),
    ("gleam-lang", "json"),
    ("lpil", "json-typedef"),
    ("MystPi", "conversation"),
    ("gleam-lang", "javascript"),
    ("lpil", "javascript-dom-parser"),
    ("Crowdhailer", "plinth"),
    ("JohnBjrk", "glimt"),
    ("defgenx", "glog"),
    ("lpil", "logging"),
    ("inoas", "stacky"),
    ("lpil", "systemd_status"),
    ("mrdimosthenis", "emel"),
    ("mrdimosthenis", "gleam_synapses"),
    ("rawhat", "glisten"),
    ("lpil", "mug"),
    ("ckreiling", "nessie"),
    ("horvathandris", "bigdecimal"),
    ("gleam-community", "maths"),
    ("aznashwan", "gleamsver"),
    ("hayleigh-dot-dev", "gleam-nibble"),
    ("bwireman", "cactus"),
    ("bwireman", "go-over"),
    ("daniellionel01", "hexdocs_offline"),
    ("imlargo", "gleam-webpush"),
    ("lpil", "wimp-pushover"),
    ("renatillas", "carotte"),
    ("renatillas", "franz"),
    ("Pevensie", "m25"),
    ("massivefermion", "blah"),
    ("mrdimosthenis", "minigen"),
    ("giacomocavalieri", "prng"),
    ("lpil", "bucket"),
    ("horvathandris", "openfeature-gleam-sdk"),
    ("kaiwu", "weapp"),
    ("kaiwu", "wechat_dev_tools"),
    ("horvathandris", "dime"),
    ("solar05", "glisbn"),
    ("lpil", "marceau"),
    ("massivefermion", "phony"),
    ("olian04", "gleam_handles"),
    ("giacomocavalieri", "birdie"),
    ("exercism", "gleam-test-runner"),
    ("inoas", "glacier"),
    ("lpil", "gleeunit"),
    ("bcpeinhardt", "testbldr"),
    ("MystPi", "dedent"),
    ("giacomocavalieri", "edit_distance"),
    ("renatillas", "g18n"),
    ("JohnBjrk", "gap"),
    ("giacomocavalieri", "glam"),
    ("brettkolodny", "gleam-hug"),
    ("SaphiraKai", "humanise"),
    ("lpil", "justin"),
    ("leobm", "phonetic_gleam"),
    ("lpil", "glance"),
    ("MAHcodes", "wink"),
    ("renatillas", "clockwork"),
    ("massivefermion", "birl"),
    ("gleam-lang", "time"),
    ("jrstrunk", "tempo"),
    ("jrstrunk", "gtz"),
    ("michaeljones", "rada"),
    ("aosasona", "crossbar"),
    ("sporto", "gleam-validator"),
    ("MystPi", "glen"),
    ("gleam-wisp", "wisp"),
    ("lpil", "atomb"),
    ("lustre-labs", "ssg"),
    ("gleam-lang", "gleam"),
    ("gleam-lang", "example-lisp-interpreter"),
    ("gleam-lang", "example-echo-server"),
    ("gleam-lang", "example-todomvc"),
    ("gleam-lang", "packages"),
    ("aosasona", "jsorm"),
    ("ghivert", "gloogle"),
    ("ryanmiville", "lustre-todomvc"),
    ("losfair", "acquire"),
    ("raineycat", "gleam-ftp"),
    ("inoas", "glychee"),
    ("tynanbe", "rad"),
    ("JonasGruenwald", "spectator"),
    ("gleam-lang", "gleam.vim"),
    ("gleam-lang", "gleam-mode"),
    ("gleam-lang", "vscode-gleam"),
    ("digitalcora", "sublime-text-gleam"),
    ("sbdchd", "neoformat"),
    ("itsgreggreg", "language-gleam"),
    ("DannyLettuce", "gleam_gedit"),
    ("0riginaln0", "lite-xl-gleam"),
]


def format_url(contributor, pkgname):
    return "https://api.github.com/repos/{0}/{1}".format(contributor, pkgname)


def get_last_3_commit_dates(url, headers):
    response = requests.get(url + "/commits?per_page=3", headers=headers)
    datestrs = [j["commit"]["committer"]["date"] for j in response.json()]
    return [format_yymmdd(dtsr) for dtsr in datestrs]


def get_repo_info(url, headers):
    response = requests.get(url, headers=headers)
    js = response.json()
    return [
        js["archived"],
        js["forks_count"],
        js["stargazers_count"],
        format_yymmdd(js["created_at"]),
    ]


def number_of_days_since(datestring):
    backthen = datetime.fromisoformat(datestring).date()
    today = date.today()
    return (today - backthen).days


def format_yymmdd(datestring):
    dt = datetime.fromisoformat(datestring).date()
    return dt.strftime("%Y-%m-%d")


if __name__ == "__main__":
    custom_headers = {
        "Authorization": "Bearer <ADD YOUR GITHUB TOKEN HERE.>",
        "Accept": "application/vnd.github+json",
    }
    for contributor, pkgname in projects:
        time.sleep(1)
        url = format_url(contributor, pkgname)
        infos = get_repo_info(url, headers=custom_headers)
        dtsrs = get_last_3_commit_dates(url, headers=custom_headers)
        print(", ".join((str(x) for x in ([contributor, pkgname] + infos + dtsrs))))
